class RoutePaths:
    ROOT = "/"
    API_PREFIX = "/api/v1"
    BASE_PATH = "http://0.0.0.0:3301"
    
    TESTS = "/tests"
    LOGIN = "/login"
    DOCS = "/docs"
    STATIC = "/static"
    PING = "/api/v1/health"
    USER = "/user"
    USER_WITH_ID = "/user/{user_id}"
    CUSTOMER = "/customer"
    CUSTOMER_WITH_ID = "/customer/{customer_id}"
    PRODUCT = "/product"
    PRODUCT_WITH_ID = "/product/{product_id}"
    PRODUCT_STOCK = "/product/stock"
    ORDER = "/order"
    ORDER_WITH_ID = "/order/{order_id}"
    ORDER_BY_CUSTOMER = "/order/by-customer/{customer_id}"
    INVOICE = "/invoice"
    INVOICE_WITH_ID = "/invoice/{invoice_id}"
    INVOICE_BY_NUMBER = "/invoice/{invoice_number}"
    INVOICE_BY_CUSTOMER = "/invoice/by-customer/{customer_id}"
    INVOICE_ORDERS = "/invoice/by-order/"
